#+TITLE: Entrepreneurship
#+AUTHOR: Ertale
#+STARTDATE: <2025-05-13 Tue>


* History, Philosophy and Definition
** What is Entrepreneur?
- Entrepreneurs are action-oriented, highly motivated individuals who take risks to achieve goals.
- Entrepreneurs are people who have the ability to see and evaluate business opportunities; the ability to gather the necessary resources to take advantage of them.
- Entrepreneurship usually requires a vision and the passion, commitment, and motivation to transmit this vision to other stakeholders, such as partners, customers, suppliers, employees, and financial backers. It also requires a willingness to take calculated risks-both personal and financial and then doing everything possible to influence the odds.
** Characteristics of Entrepreneurship
- Need for achievement
- Willingness to take risks
- Self confidence
- Innovation - continuous, purposeful search for new ideas, and their practical applications.
** Motivation for starting a Business
- The reason for small firm formation can be divided between "pull" and "push" influences.
  1) "Pull" Influences: Some individuals are attracted toward small business ownership by positive motives such as specific idea which they are convinced will work. "Pull" motives include:
     i) Desire for Independence: in several research studies as proof as a key motivator
     ii) Desire to Exploit an Opportunity: The identification of a perceived gap in the market place through personal observation or experience is also a common reason for starting a business.
     iii) Turning a Hobby or Previous Work Experience into a Business
     iv) Financial Incentive
  2) "Push" Influences: Many people are pushed to founding a new enterprise by a variety of factors:
     i) Redundancy
     ii) Unemployment(or threat of)
     iii) Disagreement with Previous Employer
** Types of Entrepreneurs
*** Artisan Entrepreneurs and Opportunistic Entrepreneurs
1) The Artisan Entrepreneurs: is a person who starts a business with primarily technical skills and little business knowledge. Artisan entrepreneur is limited to technical training. Such entrepreneur has technical job experience, but lacks good communication skills. Their approach to business decision making is characterized by the following features:
   - They are paternalistic.(This means they direct their business much as they might direct their own families)
   - They are reluctant to delegate authority
   - They use few(one or two) capital source to create their firms.
   - They define marketing strategy in terms of traditional price, quality and company reputation
   - Their sales efforts are primarily personal
   - Their time orientation is short, with little planning for future growth or change
2) Opportunistic entrepreneurs: is one who has supplemented technical education by studying such non-technical subjects as economics, law or English. An opportunistic entrepreneur is an entrepreneur who enters business with both sophisticated managerial skills and technical knowledge. Opportunistic entrepreneurs avoid paternalism, delegate authority as necessary for growth, employ various marketing strategies and types of sales efforts, obtain original capitalization from more than two sources, and plan for future growth. An example of the opportunistic entrepreneur is the small building contractor and developer who use a relatively sophisticated approach to management. Because of the complexity of the industry, successful contractors use- careful record keeping, proper budgeting, precise bidding, and systematic marketing research.
*** Entrepreneurial Teams
