#+TITLE: Learning Org-mode cont'd
#+AUTHOR: Ertale81
#+DATE: <2024-06-13 Thu>

* Creating links to files
To create a link in a file first decide which file you are going to go back and forth. Then select the header of the file by using C-c l.
After that go to your working file and create a link by typing C-c C-l then select the file you previously selected.
To follow the link type C-c C-o while your cursor is inside the link.

** Table
To draw a table you can use |column1|column2|
and simply by typing |- and TAB your table will be automatically created like the following.
| column1 | column2 |
|---------+---------|
|         |         |

** Source code
To write a source code inside
#+begin_src <language>
  
#+end_src
You can type *C-c '* to open an editor for that language and you can edit your code there.

** LaTeX Characters
\alpha \rightarrow \beta
$O(n \log n)$
\begin{align*}

\end{align*}

* Images in org mode
[[./path/to/your-image]]
press back-space on the above link to see the way how to add image.
To see the image on the buffer press C-c C-x C-v, you can customize how display it on the buffer.
